pub mod one_offs;
pub mod recurring;

// Re-export all the types and functions from one_offs for backward compatibility
pub use one_offs::{
    CreateTransactionRequest, UpdateTransactionRequest, TransactionResponse,
    create_transaction, get_transactions, get_account_transactions, 
    get_transaction, update_transaction, delete_transaction,
    // Re-export OpenAPI path structs generated by utoipa macro
    __path_create_transaction, __path_get_transactions, __path_get_account_transactions,
    __path_get_transaction, __path_update_transaction, __path_delete_transaction,
};

// Re-export recurring transaction types and functions
pub use recurring::{
    CreateRecurringTransactionRequest, UpdateRecurringTransactionRequest, RecurringTransactionResponse,
    CreateRecurringInstanceRequest, RecurringInstanceResponse, RecurringTransactionQuery,
    create_recurring_transaction, get_recurring_transactions, get_recurring_transaction,
    update_recurring_transaction, delete_recurring_transaction, create_recurring_instance,
    // Re-export OpenAPI path structs generated by utoipa macro
    __path_create_recurring_transaction, __path_get_recurring_transactions, __path_get_recurring_transaction,
    __path_update_recurring_transaction, __path_delete_recurring_transaction, __path_create_recurring_instance,
};
