pub mod one_offs;

// Re-export all the types and functions from one_offs for backward compatibility
pub use one_offs::{
    CreateTransactionRequest, UpdateTransactionRequest, TransactionResponse,
    create_transaction, get_transactions, get_account_transactions, 
    get_transaction, update_transaction, delete_transaction,
    // Re-export OpenAPI path structs generated by utoipa macro
    __path_create_transaction, __path_get_transactions, __path_get_account_transactions,
    __path_get_transaction, __path_update_transaction, __path_delete_transaction,
};
